spring:
  profile:
    active: DEV
  application:
    name: Tuum

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/tuum}
    username: postgres
    password: post1234
    driverClassName: org.postgresql.Driver

  jpa:
    spring.jpa.database-platform: postgres
    hibernate:
      ddl-auto: update   #change it accordingly in-order to set tables in db
    show-sql: true


    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  mvc:
    format:
      date-time: iso

  h2:
    console:
      enabled: true

  liquibase:
    enabled: false
    change-log: "classpath:/liquibase/changelog-master.yaml"

  rabbitmq:
    host: ${SPRING_RABBITMQ_DATASOURCE_URL:localhost}
    port: 5672
    username: guest
    password: guest

server:
  port: 8081

debug: false

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: swagger.html

logging:
  level:
    liquibase: INFO
    org:
      springframework: INFO
    com:
      assugnment:
        tuum: DEBUG
