spring:
  profile:
    active: ${PROFILE}
  application:
    name: Tuum

  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driverClassName: ${DRIVER_CLASS_NAME}

  jpa:
    database: ${DATABASE}
    hibernate:
      ddl-auto: create-drop
      show-sql: true
    properties:
      hibernate:
        dialect: ${DIALECT}
        format_sql: true
  mvc:
    format:
      date-time: iso

  h2:
    console.enabled: false

  liquibase:
    enabled: false
    change-log: "classpath:/liquibase/changelog-master.yaml"

  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE}
      max-request-size: ${MAX_REQUEST_SIZE}
      enabled: true

server:
  port: ${SERVER_PORT}

debug: false

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: swagger.html

logging:
  level:
    liquibase: INFO
    org:
      springframework: INFO
    com:
      knits:
        enterprise: DEBUG
